name: 'APIM API'
description: 'Use the APIM Command Line Interface'
inputs:
  command:  # command to run in the module
    description: 'The command to run'
    required: true
    default: 'api get'
runs:
  using: 'docker'
  image: docker://jmcabrera/apim-cli:1.3.7
  args:
    - ${{ inputs.command }}
