name: image-builder

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  image:
    if: "!contains(github.event.head_commit.message, '[NO-CI]')"
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker # see https://stackoverflow.com/a/65362210
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: jmcabrera/apim-cli
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

